### ISSUE TITLE
null pointer with artifactoryPublish with Gradle 3.2.1 + jFrog 4.4.10

### ISSUE THREAD

**Issue by seancasey42** [JFrogDev/build-info#106]
Hi,

We encountered an issue when upgrading to gradle 3.2.1 and jfrog 4.4.10. We seem to have a trouble with the artifactoryPublish task as it is throwing a null pointer exception :

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':artifactoryPublish'.
> java.lang.NullPointerException (no error message)

We set up a simple gradle 3.2.1 project and set up our main build script to look like the following:
 
apply plugin: "com.jfrog.artifactory"

buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.4.10"
  }
}

repositories {
    jcenter()
    maven { url = "{insert URL here}" }
}

We found that this is also an issue in jfog 4.4.9, but the issue goes away when we downgrade back to 4.4.5. We are curious as to if this is a bug or expected behavior.

-Thanks

**Comment by eyalbe4** [comment]
@seancasey42,
We published a snapshot version with a fix for this issue. You can install it as described in the following conversation:
https://github.com/JFrogDev/build-info/issues/101
Please let us know if the snapshot resolves the issue for you. We apologies for the inconvenience.

**Comment by eyalbe4** [comment]
@seancasey42,
Version 4.4.12 has been released and includes the fix.

**Comment by seancasey42** [comment]
@eyalbe4

Thanks for the fast response, its seems like 4.4.12 does fix this issue. 

-Thanks
