### ISSUE TITLE
Do not log message for missing publications

### ISSUE THREAD

**Issue by DanielThomas** [JFrogDev/build-info#130]
The Gradle plugin logs the following if a project doesn't configure the default publication:

    Publication named '<publication>' does not exist for project ':' in task ':artifactoryPublish'.

It's common to not want to publish the root project, but it's necessary _not_ to skip publishing on the root, otherwise the `artifactoryPublish` task dependencies are not wired correctly and publishing does not work in parallel builds.

Please decrease the logging level of this message to debug.

**Comment by eyalbe4** [comment]
@DanielThomas,
We've just pushed [this](https://github.com/JFrogDev/build-info/commit/a6c2cc80b60d9ef681e1bcdc6030a64d4457bb53) commit to change the log-level of these messages to debug.
[GAP-278](https://www.jfrog.com/jira/browse/GAP-278) tracks this change.

**Comment by DanielThomas** [comment]
Great! Thanks @eyalbe4
