### ISSUE TITLE
manual setBuildNumber causes build number matrix not to be reported

### ISSUE THREAD

**Issue by regevbr** [JFrogDev/build-info#141]
Currently, if you want to set the build number manually, you can use the clientConfig.info.setBuildNUmber() which is great but has a bad side affect - the build.number property is not attached to the artifact, thus causing the artifact to not be aware to the build that created it (and making the promote action on the build fail).
The reason for that is the code in `GradleArtifactoryClientConfigUpdater.setMissingBuildAttributes`. There, if no one set manually the build number it sets it for you and publishes the property to the artifact by doing 
```java
        if (StringUtils.isBlank(buildNumber)) {
            buildNumber = new Date().getTime() + "";
            config.info.setBuildNumber(buildNumber);
            config.publisher.addMatrixParam(BuildInfoFields.BUILD_NUMBER, buildNumber);
        }
```
But in the case you set it manually, no one adds it to the properties. The fix currently is to add the extra code yourself but I found it out the hard way by tracing your code.
The same occurs for buildName and the rest of the properties in that class.
I think the fix should be to set the matrix param only if it was not set, separately from the buildName set in the info

**Comment by eyalbe4** [comment]
@regevbr - thanks for reporting this.
I think that [this](https://github.com/JFrogDev/build-info/commit/111d3921567dacdc69d7b723793e9500357aa4fc) commit fixes the issue.
The fix hasn't been released yet, but [GAP-283](https://www.jfrog.com/jira/browse/GAP-283) tracks it.

**Comment by regevbr** [comment]
Thanks!

**Comment by eyalbe4** [comment]
@regevbr,
Since we can use [GAP-283](https://www.jfrog.com/jira/browse/GAP-283) to track this fix, I'm closing this issue.
