### ISSUE TITLE
Feature request: retry artifact publish

### ISSUE THREAD

**Issue by rspieldenner** [JFrogDev/build-info#154]
Occasionally we'll run into network hiccups when publishing artifacts via the `artifactoryPublish` task, it would be useful to be able to specify a retry count

**Comment by emkidwell** [comment]
Opened support ticket #78132 for followup.

**Comment by eyalbe4** [comment]
@rspieldenner and @emkidwell,
A retry mechanism for both uploads and downloads is implemented since version 2.7.5 of the build-info dependency. The default value for max retries is 3.

**Comment by rspieldenner** [comment]
We are running a version of the gradle plugin with a new enough bubild-info-extractor to have the retry logic. We're still occasionally hitting 503s from artifactory that don't get retried or are retried so fast to not be able to get past the hiccup.
