### ISSUE TITLE
Read user credentials from settings.xml

### ISSUE THREAD

**Issue by dsyer** [JFrogDev/build-info#46]
It's not really acceptable to have to add plaintext user credentials to a plugin configuration in maven (as far as I know that's the only way right now?). Most plugins read from user settings via a server-id. If that's possible with this plugin and I missed it then maybe it's just a documentation problem.

**Comment by eyalbe4** [comment]
Hi Dave,
You are correct. When configuring the Artifactory Plugin for Maven, to publish artifacts and build information to Artifactory, you need to define your Artifactory credentials as part of the plugin configuration inside your pom. 
For artifacts resolution from Artifactory (your build dependencies), you define your Artifactory repository like any other Maven repository and can define your server credentials in the settings.xml.
That allows you to control your resolution and deployment privileges to Artifactory more easily.
If you do not want to have your credentials directly inside the plugin configuration, you can try and put them in a different configuration file and use a Maven plugin to read them from the file, and store the credentials as project properties.

**Comment by jbaruch** [comment]
Having credentials in pom file is actually more secure and robust way to do it comparing to have them in settings.xml. 
As opposite to settings.xml, pom.xml can read environment variables and properties. By using environment variables you can both centralize the password management and securely keep the passwords outside of any maven configuration files.

**Comment by dsyer** [comment]
I guess that makes it a documentatuon problem. If you have a clear recommendation about how to do it then please can we put it in the docs for the plugin?

**Comment by jbaruch** [comment]
Will do that! 
Thanks!

**Comment by rhfrog** [comment]
A tip clarifying this has been added in the Maven Artifactory Plugin documentation.

**Comment by slawekjaranowski** [comment]
When I use properties for storing credentials, I can see plain password in build info deployed by plugin to artifactory.

Storing password in environment variable is also not effective. When we use CI server for many project we must set special variable for each plan. When in feature we want to change password we have to edit all plans.

Do you have another idea?

**Comment by eyalbe4** [comment]
@slawekjaranowski , I couldn't quite understand the challenge you're describing with using environment variables to store your credentials. Can you please elaborate?
Also, which CI Server are you using for your builds?

**Comment by slawekjaranowski** [comment]
I use Bamboo and Jenkins, and on some environment plain maven command.

We have many environment: testing, development (some in cloud) and so on ... it is about 30 environments.

Currently we manage more then 800 different plans on our CI servers.
We have tools for distributing and preparing maven settings.xml for our build system and it is easy to maintenance for us.

Now I try to use Artifactory as our binary repository and I looking for way how to distribute credentials in different way than maven settings.

Changing our configuration on CI servers by adding new task, special plugins it is not way which I prefer. I try to have our CI tasks configurations as easy as possible. 

CI servers are shared by another projects so global configuration is also not possible.

I think that possibility to get user and password from maven settings will be facilitate to another users.

**Comment by eyalbe4** [comment]
For artifact resolution and deployment to Artifactory, it is recommended to use Artifactory's CI Server plugins (or Artifactory's build tool plugins when you're not using a CI Server).
The build tool plugins for Maven and Gradle can be configured to use values from environment variables for the Artifactory credentials.
As for the CI Server Plugins (you mentioned that you use Jenkins and Bamboo) our goal is to enable you to dynamically define the credentials when you execute your build jobs remotely (through a URL).
The next release of the Bamboo Plugin will support this. See [this issue](https://www.jfrog.com/jira/browse/BAP-281). We plan to implement similar functionality into the Jenkins Plugin, allowing you set a Jenkins variable (or environment variable) for the deployer or resolver credentials.
If you decide to adopt this approach, you'll need to put in place a script that sets the credentials as environment variables and have your build jobs use them.
