### ISSUE TITLE
Next build-info-extractor-gradle release

### ISSUE THREAD

**Issue by AurelienLourot** [JFrogDev/build-info#62]
Hi JFrog, thanks for having merged #57. At TomTom we'd need this feature and would like to know if you have any plan of creating a release version and publishing it to a public artifact repository soon? Thanks a lot.

@martinm82, @maikelvdh, @ffung

**Comment by eyalbe4** [comment]
Hi @AurelienLourot ,
Thanks again for the awesome code contributions!
We don't yet have a final release date for the next version of the Gradle Artifactory Plugin, but it should be released during the next few weeks.

**Comment by StevenACoffman** [comment]
Ping

**Comment by eyalbe4** [comment]
@StevenACoffman, we don't yet have a final release date for next release of the Gradle Plugin, but it should be released during the next few weeks.

**Comment by AurelienLourot** [comment]
This has been released in `build-info-extractor-gradle:4.0.0`, thanks!
