### ISSUE TITLE
Gradle plugin, multiple repositories in the same artifactory

### ISSUE THREAD

**Issue by paulikt** [JFrogDev/build-info#76]
Please, prove me wrong! :)

No matter how hard am I trying, I just can't configure the gradle plugin to use both repositories in my artifactory. I have tried the following approaches:

Duplicating the repository block:
```gradle
artifactory {
  contextUrl = "http://artifactory.example.com/artifactory"
  resolve {
    contextUrl = "http://artifactory.example.com/artifactory"
    repository {
      repoKey  = 'libs-release'
      username = "${artifactory_user}"
      password = "${artifactory_password}"
      maven    = true
    }
    repository {
      repoKey  = 'libs-snapshot'
      username = "${artifactory_user}"
      password = "${artifactory_password}"
      maven    = true
    }
  }
}
```

Duplicating the resolve block:
```gradle
artifactory {
  contextUrl = "http://artifactory.example.com/artifactory"
  resolve {
    contextUrl = "http://artifactory.example.com/artifactory"
    repository {
      repoKey  = 'libs-release'
      username = "${artifactory_user}"
      password = "${artifactory_password}"
      maven    = true
    }
  }
  resolve {
    contextUrl = "http://artifactory.example.com/artifactory"
    repository {
      repoKey  = 'libs-snapshot'
      username = "${artifactory_user}"
      password = "${artifactory_password}"
      maven    = true
    }
  }
}
```

Duplicating the whole artifactory block:
```gradle
artifactory {
  contextUrl = "http://artifactory.example.com/artifactory"
  resolve {
    contextUrl = "http://artifactory.example.com/artifactory"
    repository {
      repoKey  = 'libs-release'
      username = "${artifactory_user}"
      password = "${artifactory_password}"
      maven    = true
    }
  }
}
artifactory {
  contextUrl = "http://artifactory.example.com/artifactory"   
  resolve {
    contextUrl = "http://artifactory.example.com/artifactory"
    repository {
      repoKey  = 'libs-snapshot'
      username = "${artifactory_user}"
      password = "${artifactory_password}"
      maven    = true
    }
  }
}
 ```

This is my first approach on using gradle, so there is a good chance, that I am missing something.

Is it a bug, a missing feature or just a bad approach?

**Comment by eyalbe4** [comment]
Hi @paulikt,
What is your final goal? Are you trying to deploy all of your build artifacts to more than one repository in the same Artifactory instance?

**Comment by paulikt** [comment]
I am not trying to deploy. I am trying to gather artifacts for the build process from different repositories of the same artifactory. The problem is, that the artifactory requires authentication for both repos, and there are artifacts in the libs-snapshot repo referencing artifacts in the libs-release repo.

So I need a configuration in which every dependency is searched in every repository (including maven central). This works well using the gradle maven plugin like this, as long as no authentication is required. 

```gradle
repositories {
    maven { url "http://artifactory.example.com/artifactory/libs-snapshot" }
    maven { url "http://artifactory.example.com/artifactory/libs-release" }
    maven { url "http://repo.maven.apache.org/maven2" }
}
```

But the gradle maven plugin has no(?) support for artifactory authentication. Therefore I have to use this artifactory plugin. As you can see I am only using the resolve block. I am not trying to deploy anything, just downloading.

**Comment by eyalbe4** [comment]
@paulikt,
The plugin never needed to support resolution from multiple repositories, because Artifactory supports it out of the box. Artifactory users usually create virtual repositories to aggregate local and remote repositories.

**Comment by paulikt** [comment]
@eyalbe4 ,
Thanks, you have made a good point on finding the solution. 

For future reference the solution is the following:
I was able to configure my artifactory to show both of my local repos under the same Virtual Repository Association. After that one artifactory configuration was enough.

**Comment by nehadagar13** [comment]
Hi paulikt,
Could you please tell me how does it work for you. with one artifactory configuration.

**Comment by paulikt** [comment]
I can't remember exactly as it was a long time ago, but I was able to configure my artifactory to show
'libs-snapshot' and 'libs-release' under a third name like 'libs'.

Since then we were able to move forward and we are using the following now, which is working perfectly
```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        mavenCentral()
        google()
        maven { url 'https://maven.google.com/' }
        maven { url 'https://jitpack.io' }
        maven {
            credentials {
                username "$artifactory_user"
                password "$artifactory_password"
            }
            url "http://artifactory.example.com/artifactory/libs-snapshot"
        }
        maven {
            credentials {
                username "$artifactory_user"
                password "$artifactory_password"
            }
            url "http://artifactory.example.com/artifactory/libs-release"
        }
        maven {
            credentials {
                username "$artifactory_user"
                password "$artifactory_password"
            }
            url "http://artifactory.example.com/artifactory/plugins-release"
        }
    }
}
```
Hope this helps

**Comment by nehadagar13** [comment]
I am also using the same way as you have defined.

But for me gradle is trying to download the jars from second repository. Is there any way to filter the repository or to specify which jar should come from which repo.

whereas my requirement is : all dependencies should get download via maven-3rdparty(1st repo) except tibco jars which should get download through maven-cto-dev-3rdpartymanual-local' (2nd repo)

 ''''repositories { 
        maven {
 			url 'https://www.artifactrepository.citigroup.net/artifactory/maven-3rdparty' 
 		credentials {
                username = "${artifactory_user}"
                password = "${artifactory_password}"
            }  
        }
        
         maven {
         url 'https://www.artifactrepository.citigroup.net/artifactory/maven-cto-dev-3rdpartymanual-local'
       	 credentials {
                username = "${artifactory_user}"
                password = "${artifactory_password}"
            }
        }		
    }
artifactory {
  contextUrl = "${artifactory_contextUrl}"
  resolve {
    contextUrl = "${artifactory_contextUrl}"
    repository {
      repoKey  = 'maven-3rdparty-local'
      username = "${artifactory_user}"
      password = "${artifactory_password}"
      maven    = true
    }
  }
  resolve {
    contextUrl = "${artifactory_contextUrl}"
    repository {
      repoKey  = 'maven-cto-dev-3rdpartymanual-local'
      username = "${artifactory_user}"
      password = "${artifactory_password}"
      maven    = true
    }
  }

> }''''

Could you please share your full build.gradle file

**Comment by paulikt** [comment]
I have not tried using multiple different artifactories, sorry

**Comment by nehadagar13** [comment]
My artifactories are same ,only repositories are different
