### ISSUE TITLE
Need formal schema for build-info JSON documents

### ISSUE THREAD

**Issue by johntconklin** [JFrogDev/build-info#82]
While this project has a java library for build-info metadata, it's also the best description of the build-info format for those of us interfacing with Artifactory using other languages/tools.

While the README.md has an example build-info JSON document, it's not really sufficient.  This week I've been writing a script to upload our build metadata to Artifactory, and it's been a constant cycle of trial and error in order to determine what objects are required and which are optional, the valid types and format of data values, etc. It would be useful if this project also provided a JSON schema definition which rigorously defined the build-info metadata.

**Comment by eyalbe4** [comment]
Thanks for your input @johntconklin .
We'll try improving the readme. We'll also gladly accept contributions to the readme documentation.

**Comment by johntconklin** [comment]
I completed the first-draft of a JSON schema based on my experimentation and the existing documentation in README.md at work today.  I'm not sure it's 100% correct with regards to what fields are required and what fields are optional, especially with regards to issues and license check metadata (which I don't use), but it should be close enough, and you guys can help clarify the details.

Since I did this at work, I need to jump through some hoops in order to contribute, but I don't anticipate any problems getting approval.

**Comment by eyalbe4** [comment]
Sure @johntconklin. That would be great. Thank you. Please submit what you have, and we'll go over it and correct if needed. Issues and License BTW are optional.

**Comment by johntconklin** [comment]
@eyalbe4, I've started on getting the management approvals I'll need to contribute this.

In the mean time, where would be a good place for the new build-info-schema.json file? Should I put it in the toplevel directory?  Or should I create a new doc/ or schema/ subdirectory?  If the longer term, if someone gets inspired and creates JSON schemas for all the Artifactory REST endpoints, it may make the most sense to create a single repository specifically for that...

**Comment by eyalbe4** [comment]
@johntconklin, I think that for now, we can put it in the existing readme.md file, in a new section next to the one containing the existing build-info example. If needed, we will modify the documentation structure in the future following additional contributions.

**Comment by johntconklin** [comment]
@eyalbe4,

Before I raise a pull request, please take a look at the README.md 
in my fork and let me know what you think.

Some notes on the build-info JSON schema.

* Most string types do not define minimum or maximum sizes or
  validation patterns.  For example, it's not clear to me whether
  the "type" property of artifacts and dependencies can be arbitrary
  strings, or if there is a list of acceptable types. Similarly, it's
  not clear whether there is a fixed set of "scopes".

* I've defined artifact and dependency objects to require a md5 hash,
  a sha1 hash, or both.  That being said, I've been able to upload
  build-info JSON without either, although Artifactory reports "No
  path found (externally resolved or deleted/overwritten)", so this
  may be considered too restrictive. If so, we can remove the some 
  of the complexity for these object types.

* I haven't set additionalProperties to false, so objects with extra
  properties not defined by the schema will still validate. I'm torn
  on this one. Minor additions will still validate, but so will mistakes.

* Object and data type descriptions were adapted from example in
  README.md. Those that didn't have a description there, don't have 
  a description in the schema.

* Since don't use licenseControl, buildRetention, issues, or
  governance objects, I've marked every property as required.  This
  may or may not be true.

We can address some of these issues before the changes are merged,
others can wait until afterwards.

**Comment by eyalbe4** [comment]
I looked at the README.md at your fork. Looks good @@johntconklin!
Here are answers to your questions:
1. The type property of artifacts and dependencies can be every string. The same goes for scopes.
2. SHA1 and MD5 both should be required, because that's how Artifactory is able to perform operations (such as promotion)
on a build. Artifactory also uses the checksum to determine and display the path of of each artifact in the build UI.
3. Question: If you look at the "Build info json format", you'll see that it can include properties such as env vars and system
properties (in the exanple at the README - "buildInfo.env.JAVA_HOME". The "version", "name", "number" etc. are at the same
level of "properties" and not inside it. I think it should be corrected in the schema.
4. I'm not sure I understabd your question about the additionalProperties. Can you please clerify?
5. You're correct - not aall fields have a description. We can add them later.
6. As for the required fields, licenseControl and issues are good. In buildRetention however, only one of the following is required: either minimumBuildDate or count (it is okay to send both).

**Comment by johntconklin** [comment]
Thanks @eyalbe4.

I've updated my fork in response to your questions.

* I've changed the buildRetention object schema to require the count and/or minimumBuildDate properties.

* There can be some confusion because the build-info JSON and the JSON schema both use the property "properties".

  That being said, my first version didn't support the module "properties" property because I wasn't sure how to represent the open-ended set of properties that can be provided. Since then, I've re-read the JSON schema specification and figured out how to use "patternProperties" to match all property names and constrain the values to strings.

  I've added this to the schema.

* If additionalProperties is set to false in the build-info object definitions, a build-info JSON document will fail to validate if any additional properties are specified. There are cases where this could be considered a good thing, and there are other cases where this could be considered bad.

  For example, suppose the user has a typo in the code (or template) that they're using to generate build-info and instead of "buildRetention" they have "bldRetention". This would validate, and the user may not realize Artifactory is not taking the desired build retention policy into account. But if you added a new "foo" property in a future Artifactory release, the schema wouldn't necessarily have to be updated to account for that new property and build-info JSON documents that used it would still validate.

  My personal preference is to set additionalProperties to false so that the JSON schema validation is strict, as I feel that's more important than being relaxed for future-proofing. If you every add additional properties, it should be easy enough for you (or me) to update the schema to match.

* Finally, do you really think both MD5 and SHA1 hashes should be required, or should it be like "count" and "minimumBuildDate" where one or the other or both are required?  My experiments with Artifactory show that it's happy with just one hash.

Thanks for your feedback.

**Comment by johntconklin** [comment]
Is the version property for agent and buildAgent objects required?  I noticed that the test file "./build-info-extractor/src/it/resources/org/jfrog/build/client/testfile.txt" contains a buildAgent object without a version.  BuildAgent.java seems to handle this as well.

**Comment by eyalbe4** [comment]
Hi @johntconklin,
* I also think it is better to be stricked to avoid mistakes in the json, and therefore 
set additionalProperties to false.

* Already mentioned this in a previous message. Just pasting this 
again because I saw it hadn't yet been changed in your repository:
If you look at the "Build info json format", you'll see that it can include properties such as env vars and system properties (in the exanple at the README - "buildInfo.env.JAVA_HOME". The "version", "name", "number" etc. are at the same
level of "properties" and not inside it. I think it should be corrected in the schema.

* We can leave only SHA1 as required, and allow not to add the MD5.
Artifactory uses the SHA1 to perform operations on the build artifacts and dependency. MD5
is used mostyl for Maven repositories, so I guess this can be okay.

* I've never tried deploying the build-info json without the buildAgent or version.
My concern is that the UI of Artifactory will be negatively effected by this. I suggest
you give it try and eploy without those sections. If the build UI for this
specific build in Artifactory look okay, then I guess we can leave this as not required.

**Comment by johntconklin** [comment]
Hi @eyalbe4,

I think we're very close now.

* I've changed the schema to set "additionalProperties" to false on all objects.
* Thanks for repeating that. I didn't notice that there is a "properties" property at the top level as well as for each module.  I've changed the schema so the "properties" property can be provided at either location.
* I've changed the schema to make both MD5 and SHA1 required properties of attributes and dependencies objects. It is generally easier to relax this in the future if it turns out to be too strict, than it will be to tighten it if it's too loose.
* When testing the schema with ./build-info-extractor/src/it/resources/org/jfrog/build/client/testfile.txt, I discovered that it defined a "LicenseViolationRecipients" list in addition to "licenseViolationsRecipientsList".  I added the new property, but additional changes are probably necessary to indicate whether one or the other or both are required.
* I've left the "version" property of "agent" and "buildAgent" objects as required.  However, this means that testfile.txt does not validate, as it's missing "version" in the "buildAgent" object definition.

**Comment by eyalbe4** [comment]
Looks really good @johntconklin!

* Either licenseViolationRecipients or licenseViolationsRecipientsList should be used.
Artifactory actually takes licenseViolationsRecipientsList (which is a Space-separated string) and turns it into licenseViolationRecipients
(a string array), so one of them should be mandatory.
 
* I think that "properties" is duplicated here:
```groovy
  "properties": {
    "properties": {
      "type": "object",
      "description": "Environment variables and properties collected from the CI server",
      "patternProperties": {
        "^.+$": {
          "type": "string"
        }
      }
    },
```

Shouldn't it be changed into?
```groovy
  "properties": {
    "type": "object",
    "description": "Environment variables and properties collected from the CI server",
    "patternProperties": {
      "^.+$": {
        "type": "string"
    }
  },
```

**Comment by johntconklin** [comment]
Hi @eyalbe4 

The "properties" keyword is confusing because it is both a property in the JSON-schema schema and the build-info schema.  The "outer" properties is part of the JSON-schema schema, where it defines the list of properties that are allowed in the build info schema (e.g. "properties", "version", "name", "number", "type", "buildAgent", etc.).  The "inner" properties is part of the build-info schema itself, where we define the type of properties that are provided by the CI server.  

Since this is an open ended set of property names, I'm using a "patternProperties" with a regex to say that any string is allowed (we can tighten the regex if Artifactory only supports a subset, e.g. only alphanumeric chars, etc.)

I can move the "inner" properties definition so it's not immediately adjacent to the "outer" properties definition if you think that's warranted.  I left it first because the example build-info json earlier in the file also has it first.

**Comment by johntconklin** [comment]
I've updated the schema to handle the licenseControl object's licenseViolationRecipients and licenseViolationsRecipientsList properties.

With this change, I'm pretty much at the end of what I can do with the schema definition.  

However If you have additional examples you can share, especially examples from each of your supported plugins, and examples that provide "licenseControl", "governance", and "issues" objects, I'm willing to run them through a schema validator and fix any remaining nits to ensure that the schema represents reality.

**Comment by eyalbe4** [comment]
@johntconklin, thanks again for the great work. If you send your mailing address to: eyalb@jfrog.com, we'll make sure to send you a JFrog T-shirt.
I think you can submit the pull request (please make sure to sign [JFrog CLA](https://www.jfrog.com/confluence/display/OSS/How+to+Contribute) so that I can merge the new content.

**Comment by johntconklin** [comment]
Hi @eyalbe4.  I've executed the CLA.  No worries on the T-Shirt, as I received one at a recent meetup at jFrog's Santa Clara office.

**Comment by eyalbe4** [comment]
https://github.com/JFrogDev/build-info/pull/83 merged.

**Comment by inorton** [comment]
Hi Guys,

I'm having some odd problems related to this.  I am uploading a buildinfo with some artifacts, when I navigate to my artifact it shows my new "build" in the builds tab list, yet if I try to go the other way and browse the modules from the new "build" I get "(externally resolved or deleted/overwritten)" in the modules list (file names are correct).

My buildinfo was uploaded with correct sha1, md5 and name for each artifact item.  It seems odd that the relationship has been added in one direction and not the other. If I'd got it wrong I'd have expected neither direction.

Really sorry if this is the wrong place to ask this.

Thanks,

**Comment by johntconklin** [comment]
I encountered the same problem. It turns out you also need to have the build.name and build.number properties set on the uploaded artifact itself. This requirement wasn't in the Artifactory REST API documentation at the time, but is now.

**Comment by inorton** [comment]
@johntconklin thank-you! that worked perfectly!
