### ISSUE TITLE
up-to-date check for jarAll task does not work

### ISSUE THREAD

**Issue by epeee** [JFrogDev/build-info#95]
Let's assume we just have a change in the build-info-extractor-gradle project. While executing a gradle build we end up in:

> :build-info-extractor-gradle:compileJava UP-TO-DATE
> :build-info-extractor-gradle:compileGroovy
> :build-info-extractor-gradle:processResources UP-TO-DATE
> :build-info-extractor-gradle:classes
> :build-info-extractor-gradle:jar
> :build-info-extractor-gradle:jarAll UP-TO-DATE
> :build-info-extractor-gradle:assemble

The jarAll task is reported as UP-TO-DATE although we had some changes in the code and classes as well as jar task got executed. As a result the uberJar does not contain the latest changes.

**Comment by eyalbe4** [comment]
Thanks for the pull request @epeee. It is merged.
